name: Auto Preprocessing Spotify

on:
  push:
    branches: [ main ]

jobs:
  run-preprocessing-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run Automate Script
        # Gunakan tanda kutip dua (") karena nama file Anda mengandung spasi
        run: |
          python "preprocessing/automate_Ridho.py"

      - name: Upload Cleaned Dataset
        uses: actions/upload-artifact@v4
        with:
          name: dataset-spotify-bersih
          # Gunakan tanda kutip juga untuk path output agar aman
          path: "preprocessing/spotify_preprocessing.csv"
